FROM ruby:3.1.2

# Pass WORKDIR environment variable form docker-compose.yml to Dockerfile
ARG WORKDIR

ENV LANG=C.UTF-8 \
    TZ=Asia/Tokyo \
    BUNDLE_PATH=vendor/bundle

WORKDIR ${WORKDIR}

RUN useradd -m -u 1000 rails
RUN chown rails ${WORKDIR}
USER rails

RUN echo "alias ll='ls -lG'" >> /rails/.bashrc
RUN gem install bundler

COPY --chown=rails Gemfile Gemfile.lock ${WORKDIR}/
# RUN bundle install
COPY --chown=rails . ${WORKDIR}

CMD ["bash"]